# patterns for all video sources
pattern.video.source: CAMRip|CAM|PDVD|TS|TELESYNC|PDVD|PTVD|PPVRip|Screener|SCR|SCREENER|DVDSCR|DVDSCREENER|BDSCR|R4|R5|R5LINE|R5.LINE|DVD|DVD5|DVD9|DVDRip|DVDR|TVRip|DSR|PDTV|SDTV|HDTV|HDTVRip|DVB|DVBRip|DTHRip|VODRip|VODR|BDRip|BRRip|BR.Rip|BluRay|Blu.Ray|BD|BDR|BD25|BD50|3D.BluRay|3DBluRay|3DBD|BR.Scr|BR.Screener|HDDVD|HDRip|WorkPrint|VHS|VCD|TELECINE|WEBRip|WEB.Rip|WEBDL|WEB.DL|WEBCap|WEB.Cap|ithd|iTunesHD|Laserdisc|AmazonHD|NetflixHD|NetflixUHD|VHSRip|LaserRip|URip|UnknownRip|MicroHD

# patterns for all video tags
pattern.video.tags: (Extended.|Ultimate.)?(Director.?s|Collector.?s|Theatrical|Ultimate|Final|Extended|Rogue|Special|Despecialized|R.Rated).(Cut|Edition|Version)|Extended|Remastered|Recut|Uncut|Uncensored|Unrated|IMAX

# patterns for stereoscopic 3D tags
pattern.video.s3d: ((H|HALF|F|FULL)[\\P{Alnum}]{0,2})?(SBS|TAB|OU)

# patterns for repack tags
pattern.video.repack: REPACK|PROPER|RERIP

# patterns for all subtitle tags
pattern.subtitle.tags: forced|HI|CC|SDH

# additional release info patterns
pattern.video.format: The.[0-9]{3,4}\\b|DivX[345]?|Xvid|AVC|[xh][.]?(?:264|265)|HEVC|dxva|3ivx|PGS|MP[E]?G[45]?|HDR[+0-9]*|DV|DoVi|Dolby.Vision|(?:Multi.)?(?:FLAC|AAC|AC3|MP3|MP4|DTS|TrueHD|DTheater|\\bDD)(?:[. ]?(?:HD|P|[+]))?(?:[. \\-\\(]*(?:Atmos|HRA|HD|MA|ES|EX|X\\b))?(?:[. \\)]*[1-9][. ]?[01])?|[1-9]ch|FLAC(?:x[2-3])?|AAC|AC3|MP3|MP4|TrueHD|Atmos|(?:HD|BD)?[M0]?(?:480|576|720|1080|2160|4320)[pix]+(?:60)?|(?<=[-])(?:2D|3D|480|576|720|1080|2160|4320)|(?:7680|3840|2040|1920|1280|720|640)x[0-9]{3,4}|(?:8|10).?bit|(?:24|30|60)FPS|Hi10[P]?|[A-Z]{2,3}.(?:[257][.][01])|(?:19|20)[0-9]+.S[0-9]+(?!.?E[0-9]+)|(?<=[0-9]+)v[0-4]|\\bCD[0-9]+\\b

# clutter file exclude pattern
pattern.clutter.excludes: (?<=[!\\-\\(\\[])(?:Sample|Trailer)|(?:Sample|Trailer)(?=[\\-\\)\\]])|(?<=[.\\-]|^)(?:(?-i:s|t)|sample|trailer|deleted|featurette|interview|scene|other|behindthescene)$|(?:NCED|NCOP|(?-i:OP|ED)\\d{0,2}(?!\\p{Alnum}))|(?:Extras|Trailers|Featurettes|Interviews|Scenes)$|Behind.the.Scenes|Deleted.and.Extended.Scenes|Deleted.Scenes

# only files smaller than 150 MB may be considered clutter
number.clutter.maxfilesize: 150000000

# known release group names
url.release-groups: release-groups.txt.xz

# blacklisted terms that will be ignored
url.query-blacklist: query-excludes.txt.xz

# list of patterns directly matching files to series names
url.series-mappings: series-mappings.txt.xz

# list of all movies (id, name, year)
url.movie-list: https://app.filebot.net/data/moviedb.txt.xz

# TheTVDB index
url.thetvdb-index: https://app.filebot.net/data/thetvdb.txt.xz

# AniDB index
url.anidb-index: https://app.filebot.net/data/anidb.txt.xz

# OpenSubtitles index
url.osdb-index: https://app.filebot.net/data/osdb.txt.xz

# disk folder matcher
pattern.diskfolder.entry: BDMV|AVCHD|HVDVD_TS|VIDEO_TS|AUDIO_TS|VCD|MovieObject.bdmv|VIDEO_TS.VOB|VTS_[0-9]+_[0-9]+.VOB

# media root folders
folder.media.roots: /Volumes:/Users:/home:/mnt:/media

# system file pattern
pattern.system.files: [.@][a-z]+|#recycle|bin|initrd|opt|sbin|var|dev|lib|proc|sys|var.defaults|etc|lost.found|root|tmp|etc.defaults|mnt|run|usr|System.Volume.Information
